import Joi from 'joi';

export const respondentValidationSchema = Joi.object({
  serial_no: Joi.string().max(20).required(),
  school_name: Joi.string().max(100).required(),
  supervisor_name: Joi.string().max(100).required(),
  collection_date: Joi.date().iso().required(),
  age: Joi.number().integer().min(15).max(19).required(),
  stay_with: Joi.number().integer().min(1).max(4).required(),
  guardian_occupation: Joi.number().integer().min(1).max(5).required(),
  guardian_occupation_other: Joi.string().max(100).optional(),
  guardian_education: Joi.number().integer().min(1).max(4).required(),
  religion: Joi.number().integer().min(1).max(5).required(),
  family_size: Joi.number().integer().min(1).required(),
  older_siblings: Joi.number().integer().valid(0, 1).required(),
  siblings_have_partners: Joi.number().integer().valid(0, 1).optional(),
  parents_give_pocket_money: Joi.number().integer().valid(0, 1).required(),
  pocket_money_adequate: Joi.number().integer().valid(0, 1).optional(),
  financial_support_source: Joi.number().integer().min(1).max(4).required(),
  guardian_visits: Joi.number().integer().valid(0, 1).required(),
  school_visitor: Joi.number().integer().min(1).max(5).optional(),
  has_rh_info: Joi.number().integer().valid(0, 1).required(),
  rh_teacher: Joi.number().integer().valid(0, 1).optional(),
  rh_parents: Joi.number().integer().valid(0, 1).optional(),
  rh_health_worker: Joi.number().integer().valid(0, 1).optional(),
  rh_friends: Joi.number().integer().valid(0, 1).optional(),
  rh_media: Joi.number().integer().valid(0, 1).optional(),
  topic_sexuality: Joi.number().integer().valid(0, 1).optional(),
  topic_abstinence: Joi.number().integer().valid(0, 1).optional(),
  topic_condoms: Joi.number().integer().valid(0, 1).optional(),
  topic_sti_hiv: Joi.number().integer().valid(0, 1).optional(),
  topic_relationships: Joi.number().integer().valid(0, 1).optional(),
  info_adequate: Joi.number().integer().valid(0, 1).required(),
});

export const respondentUpdateSchema = Joi.object({
  school_name: Joi.string().max(100).optional(),
  supervisor_name: Joi.string().max(100).optional(),
  collection_date: Joi.date().iso().optional(),
  age: Joi.number().integer().min(15).max(19).optional(),
  stay_with: Joi.number().integer().min(1).max(4).optional(),
  guardian_occupation: Joi.number().integer().min(1).max(5).optional(),
  guardian_occupation_other: Joi.string().max(100).optional(),
  guardian_education: Joi.number().integer().min(1).max(4).optional(),
  religion: Joi.number().integer().min(1).max(5).optional(),
  family_size: Joi.number().integer().min(1).optional(),
  older_siblings: Joi.number().integer().valid(0, 1).optional(),
  siblings_have_partners: Joi.number().integer().valid(0, 1).optional(),
  parents_give_pocket_money: Joi.number().integer().valid(0, 1).optional(),
  pocket_money_adequate: Joi.number().integer().valid(0, 1).optional(),
  financial_support_source: Joi.number().integer().min(1).max(4).optional(),
  guardian_visits: Joi.number().integer().valid(0, 1).optional(),
  school_visitor: Joi.number().integer().min(1).max(5).optional(),
  has_rh_info: Joi.number().integer().valid(0, 1).optional(),
  rh_teacher: Joi.number().integer().valid(0, 1).optional(),
  rh_parents: Joi.number().integer().valid(0, 1).optional(),
  rh_health_worker: Joi.number().integer().valid(0, 1).optional(),
  rh_friends: Joi.number().integer().valid(0, 1).optional(),
  rh_media: Joi.number().integer().valid(0, 1).optional(),
  topic_sexuality: Joi.number().integer().valid(0, 1).optional(),
  topic_abstinence: Joi.number().integer().valid(0, 1).optional(),
  topic_condoms: Joi.number().integer().valid(0, 1).optional(),
  topic_sti_hiv: Joi.number().integer().valid(0, 1).optional(),
  topic_relationships: Joi.number().integer().valid(0, 1).optional(),
  info_adequate: Joi.number().integer().valid(0, 1).optional(),
}).min(1);
