-- KEMRI RH Survey - Supabase one-shot setup
-- Generated as an initial migration for Supabase CLI workflows.

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.respondents (
  id bigint generated by default as identity primary key,

  serial_no varchar(20) not null unique,
  school_name varchar(100) not null,
  supervisor_name varchar(100) not null,
  collection_date date not null,

  age int not null check (age between 15 and 19),
  stay_with int not null check (stay_with between 1 and 4),

  guardian_occupation int not null check (guardian_occupation between 1 and 5),
  guardian_occupation_other varchar(100),
  guardian_education int not null check (guardian_education between 1 and 4),
  religion int not null check (religion between 1 and 5),

  family_size int not null check (family_size > 0),
  older_siblings int not null check (older_siblings in (0, 1)),
  siblings_have_partners int check (siblings_have_partners in (0, 1)),

  parents_give_pocket_money int not null check (parents_give_pocket_money in (0, 1)),
  pocket_money_adequate int check (pocket_money_adequate in (0, 1)),

  financial_support_source int not null check (financial_support_source between 1 and 4),
  guardian_visits int not null check (guardian_visits in (0, 1)),
  school_visitor int check (school_visitor between 1 and 5),

  has_rh_info int not null check (has_rh_info in (0, 1)),

  rh_teacher int not null default 0 check (rh_teacher in (0, 1)),
  rh_parents int not null default 0 check (rh_parents in (0, 1)),
  rh_health_worker int not null default 0 check (rh_health_worker in (0, 1)),
  rh_friends int not null default 0 check (rh_friends in (0, 1)),
  rh_media int not null default 0 check (rh_media in (0, 1)),

  topic_sexuality int not null default 0 check (topic_sexuality in (0, 1)),
  topic_abstinence int not null default 0 check (topic_abstinence in (0, 1)),
  topic_condoms int not null default 0 check (topic_condoms in (0, 1)),
  topic_sti_hiv int not null default 0 check (topic_sti_hiv in (0, 1)),
  topic_relationships int not null default 0 check (topic_relationships in (0, 1)),

  info_adequate int not null check (info_adequate in (0, 1)),

  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  respondent_id bigint not null references public.respondents(id) on delete cascade,
  action varchar(50) not null,
  changed_fields jsonb,
  changed_by varchar(100),
  changed_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_respondents_serial_no on public.respondents(serial_no);
create index if not exists idx_respondents_school_name on public.respondents(school_name);
create index if not exists idx_respondents_collection_date on public.respondents(collection_date);
create index if not exists idx_respondents_created_at on public.respondents(created_at desc);
create index if not exists idx_audit_logs_respondent_id on public.audit_logs(respondent_id);
create index if not exists idx_audit_logs_changed_at on public.audit_logs(changed_at desc);

drop trigger if exists trg_respondents_updated_at on public.respondents;
create trigger trg_respondents_updated_at
before update on public.respondents
for each row
execute function public.set_updated_at();

-- Security baseline for backend-only access.
-- The server uses SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
alter table public.respondents enable row level security;
alter table public.audit_logs enable row level security;

revoke all on table public.respondents from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;

commit;
